"""remove manager fields and update status default

Revision ID: 0d62fdb8db22
Revises: 37f52a6ac6b8
Create Date: 2026-05-08 13:37:35.637414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d62fdb8db22'
down_revision = '37f52a6ac6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)
        batch_op.drop_constraint(batch_op.f('overtime_requests_manager_decision_by_fkey'), type_='foreignkey')
        batch_op.drop_column('manager_note')
        batch_op.drop_column('manager_decision_by')
        batch_op.drop_column('manager_decision_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_decision_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manager_decision_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manager_note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('overtime_requests_manager_decision_by_fkey'), 'employees', ['manager_decision_by'], ['id'])
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
