"""Add early_leave_minutes to Attendance model

Revision ID: 49305570c9c7
Revises: 8ef0316da466
Create Date: 2026-06-24 00:13:12.006795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49305570c9c7'
down_revision = '8ef0316da466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_leave_minutes', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('early_leave_minutes')

    # ### end Alembic commands ###
