"""sync employee relationships

Revision ID: 847dd96147c7
Revises: def57f8ad206
Create Date: 2026-05-12 09:00:42.357490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847dd96147c7'
down_revision = 'def57f8ad206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
