"""update file_upload model and enum

Revision ID: 8ef0316da466
Revises: ed4b229451af
Create Date: 2026-05-26 08:08:45.837635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef0316da466'
down_revision = 'ed4b229451af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('file_uploads_complaint_id_fkey'), type_='foreignkey')
        batch_op.drop_column('complaint_id')

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('file_uploads_complaint_id_fkey'), 'complaints', ['complaint_id'], ['id'])
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    # ### end Alembic commands ###
