"""sync payroll complaint relationships

Revision ID: d4ed9284e08b
Revises: c6cb2272e6bb
Create Date: 2026-05-12 09:52:20.376589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ed9284e08b'
down_revision = 'c6cb2272e6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
