"""add employee relationships

Revision ID: def57f8ad206
Revises: 0d62fdb8db22
Create Date: 2026-05-12 08:49:21.099025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def57f8ad206'
down_revision = '0d62fdb8db22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
