"""upgrade salary model to store static snapshots

Revision ID: ed4b229451af
Revises: d4ed9284e08b
Create Date: 2026-05-24 10:20:49.587350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4b229451af'
down_revision = 'd4ed9284e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_days', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_leave_types_code'), ['code'], unique=True)

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=0)

    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_allowance', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('responsibility_allowance', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('overtime_salary', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('insurance', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('number_of_dependents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('family_deduction', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_column('family_deduction')
        batch_op.drop_column('number_of_dependents')
        batch_op.drop_column('tax')
        batch_op.drop_column('insurance')
        batch_op.drop_column('overtime_salary')
        batch_op.drop_column('responsibility_allowance')
        batch_op.drop_column('lunch_allowance')

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_types_code'))
        batch_op.drop_column('default_days')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
